const REVIEW_DATA = [
    {
        "exam": "EXAM 1: SEM II 2021/2022",
        "title": "Q1: Extended Dijkstra's Algorithm (20 marks)",
        "question": "Extend Dijkstra's algorithm for finding the length of a shortest path between two vertices in a weighted simple connected graph so that a shortest path between these vertices is constructed.",
        "intuition": "We maintain a **predecessor array** that records the previous vertex on the shortest path to each vertex. The algorithm returns both the shortest distance and the path.",
        "code": "import heapq\n\ndef dijkstra_with_path(graph, source, target):\n    \"\"\"\n    Dijkstra's algorithm that finds the shortest path from source to target.\n    graph: dict {vertex: {neighbor: weight, ...}, ...}\n    Returns: (distance, path_list) or (None, []) if no path exists.\n    \"\"\"\n    # Initialize distances and predecessors\n    distances = {v: float('inf') for v in graph}\n    predecessors = {v: None for v in graph}\n    distances[source] = 0\n\n    # Priority queue: (distance, vertex)\n    pq = [(0, source)]\n    visited = set()\n\n    while pq:\n        current_dist, u = heapq.heappop(pq)\n        if u in visited:\n            continue\n        visited.add(u)\n\n        # If we reached the target, we can stop early\n        if u == target:\n            break\n\n        # Relax edges\n        for v, weight in graph[u].items():\n            if v not in visited:\n                new_dist = current_dist + weight\n                if new_dist < distances[v]:\n                    distances[v] = new_dist\n                    predecessors[v] = u\n                    heapq.heappush(pq, (new_dist, v))\n\n    # Reconstruct path\n    if distances[target] == float('inf'):\n        return None, []   # no path\n\n    path = []\n    current = target\n    while current is not None:\n        path.append(current)\n        current = predecessors[current]\n    path.reverse()   # source to target\n    return distances[target], path\n\n# Example usage (sample graph)\nif __name__ == \"__main__\":\n    G = {\n        'a': {'b': 4, 'c': 2},\n        'b': {'a': 4, 'c': 1, 'd': 5},\n        'c': {'a': 2, 'b': 1, 'd': 8, 'e': 10},\n        'd': {'b': 5, 'c': 8, 'e': 2, 'z': 6},\n        'e': {'c': 10, 'd': 2, 'z': 3},\n        'z': {'d': 6, 'e': 3}\n    }\n    dist, path = dijkstra_with_path(G, 'a', 'z')\n    print(f\"Shortest distance: {dist}\")\n    print(f\"Shortest path: {' -> '.join(path)}\")",
        "execution": "**Complexity:** O((V+E) log V) with a binary heap.\n\n---"
    },
    {
        "exam": "EXAM 1: SEM II 2021/2022",
        "title": "Q2: Dijkstra's Algorithm with Negative Weights (20 marks)",
        "question": "Show that Dijkstra's algorithm may not work if edges can have negative weights.",
        "intuition": "Dijkstra\u2019s algorithm relies on the fact that once a vertex is settled (added to S), its shortest distance is final. With negative edges, a later path through a settled vertex could improve distances to other vertices, but Dijkstra never reconsiders settled vertices.\n\n**Counterexample graph:**\n\n- Vertices: A, B, C, D\n- Edges: A\u2192B (5), A\u2192C (1), C\u2192D (-3), D\u2192B (2)",
        "code": "",
        "execution": "**Step-by-step failure:**\n\n1. Initialize: L(A)=0, L(B)=\u221e, L(C)=\u221e, L(D)=\u221e.\n2. Select A: update L(B)=5, L(C)=1. S={A}.\n3. Select C (smallest distance 1): update L(D)=1+(-3)=-2. S={A,C}.\n4. Select D (smallest -2): update L(B)= -2+2=0. S={A,C,D}.\n5. Select B (0): S={A,C,D,B}.\n   Dijkstra reports L(B)=0, which is correct in this example, but the issue arises because C was settled before the negative path was discovered. If there were further vertices, C would never be reconsidered.\n\n**Correct shortest path** A\u2192C(1)\u2192D(-3)\u2192B(2) = 0, but Dijkstra would have missed any path that uses C after it is settled.\n\n**Conclusion:** Dijkstra is only correct for non\u2011negative edge weights.\n\n---"
    },
    {
        "exam": "EXAM 1: SEM II 2021/2022",
        "title": "Q3: Kruskal's Algorithm (20 marks)",
        "question": "The roads represented by the graph in Figure Q3 are all unpaved. The lengths of the roads between pairs of towns are represented by edge weights. Use Kruskal's algorithm to find which roads should be paved so that there is a path of paved roads between each pair of towns so that a minimum road length is paved.\n\n**Table (sorted by weight):**\n\n| Rank | Edge (Town - Town)        | Weight |\n| ---- | ------------------------- | ------ |\n| 1    | Deep Springs \u2013 Oasis      | 10     |\n| 2    | Gold Point \u2013 Lida         | 12     |\n| 3    | Silver Pea \u2013 Goldfield    | 20     |\n| 4    | Dyer \u2013 Oasis              | 21     |\n| 5    | Oasis \u2013 Silver Pea        | 23     |\n| 6    | Manhattan \u2013 Tonopah       | 25     |\n| 7    | Dyer \u2013 Silver Pea         | 25     |\n| 8    | Oasis \u2013 Lida              | 25     |\n| 9    | Lida \u2013 Goldfield          | 29     |\n| 10   | Deep Springs \u2013 Gold Point | 30     |\n| 11   | Tonopah \u2013 Goldfield       | 35     |\n| 12   | Dyer \u2013 Tonopah            | 40     |\n| 13   | Gold Point \u2013 Beatty       | 45     |\n| 14   | Tonopah \u2013 Warm Springs    | 55     |\n| 15   | Manhattan \u2013 Warm Springs  | 60     |\n| 16   | Goldfield \u2013 Beatty        | 70     |\n| 17   | Dyer \u2013 Manhattan          | 80     |",
        "intuition": "We apply Kruskal's algorithm: sort edges ascending, add if no cycle. The towns are 11 vertices, so MST has 10 edges.",
        "code": "class UnionFind:\n    def __init__(self, n):\n        self.parent = list(range(n))\n        self.rank = [0]*n\n\n    def find(self, x):\n        while self.parent[x] != x:\n            self.parent[x] = self.parent[self.parent[x]]\n            x = self.parent[x]\n        return x\n\n    def union(self, x, y):\n        rx, ry = self.find(x), self.find(y)\n        if rx == ry:\n            return False\n        if self.rank[rx] < self.rank[ry]:\n            self.parent[rx] = ry\n        elif self.rank[rx] > self.rank[ry]:\n            self.parent[ry] = rx\n        else:\n            self.parent[ry] = rx\n            self.rank[rx] += 1\n        return True\n\n# List of edges from table\nedges = [\n    (\"Deep Springs\", \"Oasis\", 10),\n    (\"Gold Point\", \"Lida\", 12),\n    (\"Silver Pea\", \"Goldfield\", 20),\n    (\"Dyer\", \"Oasis\", 21),\n    (\"Oasis\", \"Silver Pea\", 23),\n    (\"Manhattan\", \"Tonopah\", 25),\n    (\"Dyer\", \"Silver Pea\", 25),\n    (\"Oasis\", \"Lida\", 25),\n    (\"Lida\", \"Goldfield\", 29),\n    (\"Deep Springs\", \"Gold Point\", 30),\n    (\"Tonopah\", \"Goldfield\", 35),\n    (\"Dyer\", \"Tonopah\", 40),\n    (\"Gold Point\", \"Beatty\", 45),\n    (\"Tonopah\", \"Warm Springs\", 55),\n    (\"Manhattan\", \"Warm Springs\", 60),\n    (\"Goldfield\", \"Beatty\", 70),\n    (\"Dyer\", \"Manhattan\", 80)\n]\n\n# Get unique vertices\nvertices = set()\nfor u, v, w in edges:\n    vertices.add(u); vertices.add(v)\nvertex_list = list(vertices)\nindex = {v:i for i,v in enumerate(vertex_list)}\nuf = UnionFind(len(vertex_list))\n\nmst_edges = []\ntotal_weight = 0\n\nfor u, v, w in edges:\n    if uf.union(index[u], index[v]):\n        mst_edges.append((u, v, w))\n        total_weight += w\n        if len(mst_edges) == len(vertices)-1:\n            break\n\nprint(\"Edges in MST:\", mst_edges)\nprint(\"Total length:\", total_weight)",
        "execution": "**Resulting MST edges (in order added):**\n\n1. Deep Springs \u2013 Oasis (10)\n2. Gold Point \u2013 Lida (12)\n3. Silver Pea \u2013 Goldfield (20)\n4. Dyer \u2013 Oasis (21)\n5. Oasis \u2013 Silver Pea (23)\n6. Manhattan \u2013 Tonopah (25)\n7. Oasis \u2013 Lida (25)\n8. Lida \u2013 Goldfield (29)\n9. Deep Springs \u2013 Gold Point (30)\n10. Tonopah \u2013 Goldfield (35)\n\nTotal weight = 10+12+20+21+23+25+25+29+30+35 = 230.\n\n---"
    },
    {
        "exam": "EXAM 1: SEM II 2021/2022",
        "title": "Q4: Maximum Spanning Tree Algorithm (20 marks)",
        "question": "A maximum spanning tree of a connected weighted undirected graph is a spanning tree with the largest possible weight. Devise an algorithm similar to Kruskal's algorithm for constructing a maximum spanning tree of a connected weighted graph.",
        "intuition": "We sort edges in **descending** order of weight and add if no cycle forms. This is the opposite of Kruskal\u2019s for minimum spanning tree.",
        "code": "def maximum_spanning_tree(graph_edges, num_vertices):\n    \"\"\"\n    graph_edges: list of (u, v, weight)\n    num_vertices: total number of vertices\n    Returns: list of edges in the maximum spanning tree and total weight.\n    \"\"\"\n    # Sort edges by weight descending\n    edges_sorted = sorted(graph_edges, key=lambda x: x[2], reverse=True)\n    uf = UnionFind(num_vertices)\n    mst = []\n    total = 0\n    for u, v, w in edges_sorted:\n        if uf.union(u, v):\n            mst.append((u, v, w))\n            total += w\n            if len(mst) == num_vertices - 1:\n                break\n    return mst, total",
        "execution": "**Correctness:** The same cut property applies; picking the heaviest edge across a cut is safe for a maximum spanning tree.\n\n**Complexity:** O(E log E) for sorting.\n\n---"
    },
    {
        "exam": "EXAM 1: SEM II 2021/2022",
        "title": "Q5: Minimum Spanning Forest (20 marks)",
        "question": "A minimum spanning forest in a weighted graph is a spanning forest with minimal weight. Explain how Prim's and Kruskal's algorithms can be adapted to construct minimum spanning forests.",
        "intuition": "A minimum spanning forest is the union of MSTs for each connected component.\n\n**Adaptation of Kruskal:**\nRun the standard Kruskal algorithm, but do not stop after (V-1) edges; process all edges. The algorithm naturally handles disconnected graphs because it will add edges within each component and skip edges that would connect different components (which don't exist). The result is a forest that is minimal.\n\n**Adaptation of Prim:**\nFor each vertex that hasn\u2019t been visited, start a new Prim run. This builds an MST for each connected component.",
        "code": "def prim_msf(graph, num_vertices):\n    \"\"\"\n    graph: adjacency list with weights, e.g., {0: [(1,5), (2,3)], ...}\n    Returns: list of edges in the minimum spanning forest.\n    \"\"\"\n    visited = [False]*num_vertices\n    forest_edges = []\n    for start in range(num_vertices):\n        if not visited[start]:\n            # Prim's algorithm for this component\n            import heapq\n            pq = [(0, start, -1)]  # (weight, vertex, parent)\n            while pq:\n                w, u, parent = heapq.heappop(pq)\n                if visited[u]:\n                    continue\n                visited[u] = True\n                if parent != -1:\n                    forest_edges.append((parent, u, w))\n                for v, weight in graph[u]:\n                    if not visited[v]:\n                        heapq.heappush(pq, (weight, v, u))\n    return forest_edges",
        "execution": "**Complexity:** Same as original Prim/Kruskal, O((V+E) log V) or O(E log E).\n\n---"
    },
    {
        "exam": "EXAM 2: SEM II 2024/2025",
        "title": "Q1 \u2014 Merge Sort (25 marks total)",
        "question": "**(a)** Write a merge sort algorithm for a set of numbers {a\u2081, a\u2082, ..., a\u2099}.\n**(b)** Use the algorithm in Q1(a) to sort the numbers {9, 15, 5, 23, 11, 37, 3} in ascending order.\n**(c)** Estimate the worst-case complexity of the merge sort algorithm.",
        "intuition": "**(a)** Python implementation:",
        "code": "def merge_sort(arr):\n    \"\"\"\n    Sorts arr in ascending order using merge sort.\n    \"\"\"\n    if len(arr) <= 1:\n        return arr\n\n    # Divide the array into two halves\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n\n    # Merge the two sorted halves\n    return merge(left, right)\n\ndef merge(left, right):\n    \"\"\"\n    Merges two sorted lists into one sorted list.\n    \"\"\"\n    merged = []\n    i = j = 0\n    # Compare elements from left and right and add the smaller one\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            merged.append(left[i])\n            i += 1\n        else:\n            merged.append(right[j])\n            j += 1\n    # Append any remaining elements\n    merged.extend(left[i:])\n    merged.extend(right[j:])\n    return merged",
        "execution": "**(b)** Sorting {9, 15, 5, 23, 11, 37, 3}:\n\n- Divide: \\[9,15,5,23] and \\[11,37,3]\n- Divide further: \\[9,15] \\[5,23] and \\[11,37] \\[3]\n- Individual: \\[9] \\[15] \\[5] \\[23] \\[11] \\[37] \\[3]\n- Merge: \\[9,15] and \\[5,23] \u2192 \\[5,9,15,23]; \\[11,37] and \\[3] \u2192 \\[3,11,37]\n- Merge final: \\[5,9,15,23] and \\[3,11,37] \u2192 \\[3,5,9,11,15,23,37]\n\n**(c)** Worst-case complexity: Merge sort always divides into halves and merges in linear time, so recurrence T(n) = 2T(n/2) + O(n). By Master Theorem, T(n) = O(n log n) for all cases.\n\n---"
    },
    {
        "exam": "EXAM 2: SEM II 2024/2025",
        "title": "Q2 \u2014 Binary Search (25 marks total)",
        "question": "**(a)** Construct the basic algorithm of a binary search algorithm.\n**(b)** Construct the recursive algorithm of a binary search algorithm from Q2(a).\n**(c)** Use the algorithm in Q2(b) to search number 19 in the set {1, 2, 4, 5, 6, 7, 8, 9, 12, 13, 15, 16, 18, 19, 20, 22}.",
        "intuition": "**(a)** Iterative binary search:",
        "code": "def binary_search_iterative(arr, target):\n    \"\"\"\n    Returns index of target in sorted arr, or -1 if not found.\n    \"\"\"\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
        "execution": "**(b)** Recursive version:\n\n```python\ndef binary_search_recursive(arr, target, low, high):\n    if low > high:\n        return -1\n    mid = (low + high) // 2\n    if arr[mid] == target:\n        return mid\n    elif arr[mid] < target:\n        return binary_search_recursive(arr, target, mid+1, high)\n    else:\n        return binary_search_recursive(arr, target, low, mid-1)\n\n# Wrapper\ndef binary_search(arr, target):\n    return binary_search_recursive(arr, target, 0, len(arr)-1)\n```\n\n**(c)** Search for 19 in the given sorted set:\nArray indices 0..15.\nStep 1: low=0, high=15, mid=7, arr\\[7]=9 < 19 \u2192 search right.\nStep 2: low=8, high=15, mid=11, arr\\[11]=16 < 19 \u2192 search right.\nStep 3: low=12, high=15, mid=13, arr\\[13]=19 \u2192 found at index 13 (0\u2011based).\n\n---"
    },
    {
        "exam": "EXAM 2: SEM II 2024/2025",
        "title": "Q3 \u2014 Recursive Divide-and-Conquer (25 marks total)",
        "question": "**(a)** Compute a\u00b2\u207f where a is a nonzero real number and n is a nonnegative integer.\n**(b)** Find the lowest value of x from a finite set of n integers.\n**(c)** Estimate the time complexity of the algorithm in Q3(b).",
        "intuition": "**(a)** Compute a^(2n) = (a^n)^2. Use divide and conquer on n:",
        "code": "def power_2n(a, n):\n    \"\"\"\n    Returns a^(2n) for n >= 0.\n    \"\"\"\n    if n == 0:\n        return 1\n    # Compute a^n using fast exponentiation\n    def power(a, n):\n        if n == 0:\n            return 1\n        half = power(a, n//2)\n        if n % 2 == 0:\n            return half * half\n        else:\n            return half * half * a\n    an = power(a, n)\n    return an * an",
        "execution": "**(b)** Find minimum of an array using divide and conquer:\n\n```python\ndef find_min(arr, low, high):\n    if low == high:\n        return arr[low]\n    mid = (low + high) // 2\n    left_min = find_min(arr, low, mid)\n    right_min = find_min(arr, mid+1, high)\n    return left_min if left_min < right_min else right_min\n```\n\n**(c)** Time complexity: T(n) = 2T(n/2) + O(1). By Master Theorem, T(n) = O(n). (We must examine every element.)\n\n---"
    },
    {
        "exam": "EXAM 2: SEM II 2024/2025",
        "title": "Q4 \u2014 Graph Theory (25 marks total)",
        "question": "**(a)** Find the adjacency matrix of the weighted graph.\n**(b)** Find the adjacency list of the weighted graph.\n**(c)** Find the shortest path from vertex A to G by using Dijkstra's algorithm.\n\n**Figure Q4.1** shows a graph with vertices A, B, C, D, E, F, G and the following edges (from the figure):\n\n| Edge | Weight |\n| ---- | ------ |\n| A\u2013B  | 8      |\n| A\u2013C  | 10     |\n| B\u2013D  | 12     |\n| B\u2013E  | 11     |\n| C\u2013F  | 4      |\n| C\u2013G  | 7      |\n| D\u2013F  | 5      |\n| E\u2013G  | 9      |\n| D\u2013E  | 19     |",
        "intuition": "**(a)** Adjacency matrix (vertices in order A, B, C, D, E, F, G). Use \u221e for no edge (or 0 for no edge; we'll use 0 in matrix but \u221e is common for Dijkstra; we can show with \u221e in text).",
        "code": "A  B  C  D  E  F  G\nA  0  8 10 \u221e \u221e \u221e \u221e\nB  8  0 \u221e 12 11 \u221e \u221e\nC 10 \u221e  0 \u221e \u221e  4  7\nD \u221e 12 \u221e  0 19  5 \u221e\nE \u221e 11 \u221e 19  0 \u221e  9\nF \u221e \u221e  4  5 \u221e  0 \u221e\nG \u221e \u221e  7 \u221e  9 \u221e  0",
        "execution": "**(b)** Adjacency list:\nA: \\[(B, 8), (C, 10)]\nB: \\[(A, 8), (D, 12), (E, 11)]\nC: \\[(A, 10), (F, 4), (G, 7)]\nD: \\[(B, 12), (E, 19), (F, 5)]\nE: \\[(B, 11), (D, 19), (G, 9)]\nF: \\[(C, 4), (D, 5)]\nG: \\[(C, 7), (E, 9)]\n\n**(c)** Dijkstra from A to G:\n\n- Initialize: dist\\[A]=0, others \u221e.\n- Pop A: update B=8, C=10.\n- Pop B (8): update D=8+12=20, E=8+11=19.\n- Pop C (10): update F=10+4=14, G=10+7=17.\n- Pop F (14): update D via F = 14+5=19 (keep 20).\n- Pop E (19): update G via E = 19+9=28 (keep 17), update D via E = 19+19=38 (keep 19).\n- Pop G (17) \u2013 target reached. Shortest path: A \u2192 C \u2192 G with total weight 10+7 = 17.\n- Alternative: A\u2192B\u2192E\u2192G = 8+11+9=28, A\u2192B\u2192D\u2192F\u2192C\u2192G? Not shorter. So shortest is 17.\n\n**Dijkstra code (generic):**\n\n```python\nimport heapq\n\ndef dijkstra(graph, start, target):\n    dist = {v: float('inf') for v in graph}\n    prev = {v: None for v in graph}\n    dist[start] = 0\n    pq = [(0, start)]\n    while pq:\n        d, u = heapq.heappop(pq)\n        if d != dist[u]:\n            continue\n        if u == target:\n            break\n        for v, w in graph[u]:\n            nd = d + w\n            if nd < dist[v]:\n                dist[v] = nd\n                prev[v] = u\n                heapq.heappush(pq, (nd, v))\n    # reconstruct path\n    path = []\n    cur = target\n    while cur is not None:\n        path.append(cur)\n        cur = prev[cur]\n    path.reverse()\n    return dist[target], path\n```\n\nFor the given graph, the function returns (17, \\['A','C','G']).\n\n---"
    },
    {
        "exam": "EXAM 3: SEM I 2025/2026",
        "title": "Q1 \u2014 Bubble Sort (25 marks total)",
        "question": "**(a)** Write a bubble sort algorithm for a set of numbers {c\u2081, c\u2082, ..., c\u2099}.\n**(b)** Based on answer Q1(a), sort the numbers {7, 17, 3, 23, 11, 37, 9, 45, 15, 99} in ascending order.\n**(c)** Estimate the worst-case complexity of the bubble sort algorithm.",
        "intuition": "**(a)** Bubble sort in Python:",
        "code": "def bubble_sort(arr):\n    \"\"\"\n    Sorts arr in ascending order using bubble sort.\n    \"\"\"\n    n = len(arr)\n    for i in range(n):                # Number of passes\n        swapped = False\n        # Last i elements are already in place\n        for j in range(0, n - i - 1):\n            if arr[j] > arr[j+1]:\n                arr[j], arr[j+1] = arr[j+1], arr[j]\n                swapped = True\n        # If no swaps, array is sorted\n        if not swapped:\n            break\n    return arr",
        "execution": "**(b)** Sorting the given array:\nInitial: \\[7, 17, 3, 23, 11, 37, 9, 45, 15, 99]\nPass 1: \\[7, 3, 17, 11, 23, 9, 37, 15, 45, 99]\nPass 2: \\[3, 7, 11, 17, 9, 23, 15, 37, 45, 99]\nPass 3: \\[3, 7, 11, 9, 17, 15, 23, 37, 45, 99]\nPass 4: \\[3, 7, 9, 11, 15, 17, 23, 37, 45, 99] (no swaps in next pass)\nFinal sorted: \\[3, 7, 9, 11, 15, 17, 23, 37, 45, 99].\n\n**(c)** Worst-case complexity: O(n\u00b2) comparisons and swaps (reverse order). Best-case O(n) when already sorted.\n\n---"
    },
    {
        "exam": "EXAM 3: SEM I 2025/2026",
        "title": "Q2 \u2014 Binary Search (25 marks total)",
        "question": "**(a)** Construct the binary search algorithm with complexity O(n\u00b2).\n**(b)** Construct the recursive algorithm of a binary search algorithm based on answer Q2(a).\n**(c)** Based on answer Q2(b), search number 27 in the set {1, 2, 4, 5, 6, 7, 8, 9, 27, 13, 15, 16, 18, 19, 20, 22}.\n*(Note: Set is not sorted \u2014 27 appears before 13)*",
        "intuition": "**(a)** True binary search is O(log n). To artificially make it O(n\u00b2), we can add nested loops that do nothing before the actual search. However, the core algorithm remains O(log n). So we can write a function that performs O(n\u00b2) extra work and then a proper binary search.",
        "code": "def slow_binary_search(arr, target):\n    # Artificially add O(n\u00b2) operations\n    n = len(arr)\n    for i in range(n):\n        for j in range(n):\n            _ = i * j   # dummy\n    # Actual binary search (O(log n))\n    low, high = 0, n-1\n    while low <= high:\n        mid = (low+high)//2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
        "execution": "**(b)** Recursive version (still with extra O(n\u00b2) work at each call? That would be huge; we can just add it once at the top level or in each recursive call. For the answer, we can show the standard recursive binary search.\n\n```python\ndef recursive_binary_search(arr, target, low, high):\n    if low > high:\n        return -1\n    mid = (low+high)//2\n    if arr[mid] == target:\n        return mid\n    elif arr[mid] < target:\n        return recursive_binary_search(arr, target, mid+1, high)\n    else:\n        return recursive_binary_search(arr, target, low, mid-1)\n```\n\n**(c)** The given set is not sorted. Binary search requires a sorted array. If we sort it first, we get \\[1,2,4,5,6,7,8,9,13,15,16,18,19,20,22,27]. Searching for 27:\nIndices: 0..15.\nStep1: mid=7 (value 9) < 27 \u2192 right half.\nStep2: low=8, high=15, mid=11 (value 18) < 27 \u2192 right.\nStep3: low=12, high=15, mid=13 (value 20) < 27 \u2192 right.\nStep4: low=14, high=15, mid=14 (value 22) < 27 \u2192 right.\nStep5: low=15, high=15, mid=15 (value 27) \u2192 found at index 15.\n\n---"
    },
    {
        "exam": "EXAM 3: SEM I 2025/2026",
        "title": "Q3 \u2014 Recursive Divide-and-Conquer (25 marks total)",
        "question": "**(a)** Compute a\u2075\u207f where a is a nonzero real number and n is a nonnegative integer.\n**(b)** Find the lowest value of x from a finite set of n integers.\n**(c)** Estimate the time complexity of the algorithm based on answer Q3(b).",
        "intuition": "**(a)** Compute a^(5n) = (a^n)^5. Use fast exponentiation for a^n, then raise to 5.",
        "code": "def power_5n(a, n):\n    # compute a^n\n    def pow(a, n):\n        if n == 0:\n            return 1\n        half = pow(a, n//2)\n        if n % 2 == 0:\n            return half * half\n        else:\n            return half * half * a\n    an = pow(a, n)\n    return an ** 5   # or an*an*an*an*an",
        "execution": "**(b)** Same as Exam 2 Q3(b) \u2013 recursive min.\n\n**(c)** O(n) \u2013 must visit every element.\n\n---"
    },
    {
        "exam": "EXAM 3: SEM I 2025/2026",
        "title": "Q4 \u2014 Assignment Problem (25 marks total)",
        "question": "The assignment problem needs to solve the problem by selecting one element in each row of the cost matrix based on these conditions:\n\n- No two selected elements are in the same column; and\n- The sum is minimized.\n\n**Table Q4.1:**\n\n| Worker  Job | Job 1 | Job 2 | Job 3 | Job 4 |\n| ------------ | ----- | ----- | ----- | ----- |\n| A            | 9     | 8     | 7     | 8     |\n| B            | 7     | 4     | 3     | 4     |\n| C            | 5     | 6     | 1     | 8     |\n| D            | 6     | 2     | 9     | 7     |\n\n**(a)** Draw levels 0 and 1 of the state-space trees for the instance of the assignment problem.\n**(b)** Draw levels 0, 1 and 2 of the state-space trees for the instance of the assignment problem.\n**(c)** Draw the complete state-space trees for the instance of the assignment problem.",
        "intuition": "We use a state-space tree where each level assigns a worker. Level 0: root. Level 1: assign worker A to each job. Level 2: assign worker B, etc.\n\n**(a) Levels 0 and 1:**\n\n- Level 0: root (no assignment)\n- Level 1: four nodes: A\u21921 (cost 9), A\u21922 (cost 8), A\u21923 (cost 7), A\u21924 (cost 8)\n\n**(b) Levels 0, 1, and 2:**\n\nFrom each level-1 node, we assign worker B to a job not used.\n\n- From A\u21921 (cost 9): B\u21922 (13), B\u21923 (12), B\u21924 (13)\n- From A\u21922 (cost 8): B\u21921 (15), B\u21923 (11), B\u21924 (12)\n- From A\u21923 (cost 7): B\u21921 (14), B\u21922 (11), B\u21924 (11)\n- From A\u21924 (cost 8): B\u21921 (15), B\u21922 (12), B\u21923 (11)\n\n**(c) Complete tree:**\n\nContinue to level 3 (worker C) and level 4 (worker D). The optimal assignment is found by exploring all leaves. We compute minimal total cost.\n\nWe can systematically enumerate:\n\n- A1, B2, C3, D4: 9+4+1+7=21\n- A1, B2, C4, D3: 9+4+8+9=30\n- A1, B3, C2, D4: 9+3+6+7=25\n- A1, B3, C4, D2: 9+3+8+2=22\n- A1, B4, C2, D3: 9+4+6+9=28\n- A1, B4, C3, D2: 9+4+1+2=16  (this is good)\n- A2, B1, C3, D4: 8+7+1+7=23\n- A2, B1, C4, D3: 8+7+8+9=32\n- A2, B3, C1, D4: 8+3+5+7=23\n- A2, B3, C4, D1: 8+3+8+6=25\n- A2, B4, C1, D3: 8+4+5+9=26\n- A2, B4, C3, D1: 8+4+1+6=19\n- A3, B1, C2, D4: 7+7+6+7=27\n- A3, B1, C4, D2: 7+7+8+2=24\n- A3, B2, C1, D4: 7+4+5+7=23\n- A3, B2, C4, D1: 7+4+8+6=25\n- A3, B4, C1, D2: 7+4+5+2=18\n- A3, B4, C2, D1: 7+4+6+6=23\n- A4, B1, C2, D3: 8+7+6+9=30\n- A4, B1, C3, D2: 8+7+1+2=18\n- A4, B2, C1, D3: 8+4+5+9=26\n- A4, B2, C3, D1: 8+4+1+6=19\n- A4, B3, C1, D2: 8+3+5+2=18\n- A4, B3, C2, D1: 8+3+6+6=23\n\nMinimum cost = 16 (A1, B4, C3, D2). So optimal assignment: A\u2192Job1, B\u2192Job4, C\u2192Job3, D\u2192Job2 with total cost 16.\n\n---",
        "code": "",
        "execution": ""
    },
    {
        "exam": "EXAM 4: SEM II 2022/2023",
        "title": "Q1 \u2014 Merge Sort (24 marks total)",
        "question": "**(a)** Specify the algorithm design technique type of the merge sort algorithm.\n**(b)** Write a merge sort algorithm for a set of numbers {a\u2081, a\u2082, ..., a\u2099}.\n**(c)** Show the steps to sort the numbers {8, 13, 7, 16, 10, 22, 5} using the merge sort algorithm.\n**(d)** Estimate the best case complexity of the merge sort algorithm.\n**(e)** Estimate the average case complexity of the merge sort algorithm.\n**(f)** Estimate the worst case complexity of the merge sort algorithm.",
        "intuition": "**(a)** Divide and Conquer.\n**(b)** See Exam 2 Q1 for code.\n**(c)** Steps:\nDivide: \\[8,13,7,16,10,22,5] \u2192 \\[8,13,7] \\[16,10,22,5] \u2192 \\[8] \\[13,7] \\[16,10] \\[22,5] \u2192 \\[8] \\[13] \\[7] \\[16] \\[10] \\[22] \\[5]\nMerge: \\[8] and \\[7,13] \u2192 \\[7,8,13]; \\[16] and \\[10,22]? Actually: \\[16,10] and \\[22,5] \u2192 merge \\[16]&\\[10]\u2192\\[10,16]; \\[22]&\\[5]\u2192\\[5,22]; merge \\[10,16]&\\[5,22]\u2192\\[5,10,16,22]; then merge \\[7,8,13] and \\[5,10,16,22] \u2192 \\[5,7,8,10,13,16,22].\n**(d),(e),(f)** All O(n log n) \u2013 merge sort has the same complexity for best, average, and worst.\n\n---",
        "code": "",
        "execution": ""
    },
    {
        "exam": "EXAM 4: SEM II 2022/2023",
        "title": "Q2 \u2014 Recursive Algorithms (25 marks total)",
        "question": "**(a)** Write a recursive algorithm for computing a\u207f where a is a nonzero real number and n is a nonnegative integer.\n**(b)** Write a recursive algorithm for finding the minimum (smaller x) of a finite set of n integers.\n**(c)** Estimate the time complexity of the algorithm in Q2(b).\n**(d)** Construct a recursive version of a binary search algorithm.\n**(e)** Use the algorithm in Q2(d) to search for the number 20 in the set {1, 2, 3, 5, 6, 7, 8, 10, 12, 13, 15, 16, 18, 19, 20, 22}.",
        "intuition": "**(a)** Recursive power:",
        "code": "def power(a, n):\n    if n == 0:\n        return 1\n    if n == 1:\n        return a\n    half = power(a, n//2)\n    if n % 2 == 0:\n        return half * half\n    else:\n        return half * half * a",
        "execution": "**(b)** Recursive min (see previous).\n**(c)** O(n).\n**(d)** Recursive binary search (see previous).\n**(e)** Search 20 in the given sorted array: indices 0..15.\nStep1: mid=7 \u2192 value 10 < 20 \u2192 right.\nStep2: low=8, high=15, mid=11 \u2192 value 16 < 20 \u2192 right.\nStep3: low=12, high=15, mid=13 \u2192 value 19 < 20 \u2192 right.\nStep4: low=14, high=15, mid=14 \u2192 value 20 \u2192 found at index 14.\n\n---"
    },
    {
        "exam": "EXAM 4: SEM II 2022/2023",
        "title": "Q3 \u2014 Graph Theory (25 marks total)",
        "question": "Given the following weighted graph (table):\n\n| Source | Destination | Weight |\n| ------ | ----------- | ------ |\n| A      | B           | 4      |\n| A      | C           | 8      |\n| B      | D           | 7      |\n| C      | D           | 10     |\n| D      | E           | 12     |\n| D      | F           | 17     |\n| E      | F           | 9      |\n| E      | G           | 6      |\n| F      | G           | 9      |\n\n**(a)** Find the adjacency matrix of the weighted graph.\n**(b)** Find the adjacency list of the weighted graph.\n**(c)** Find the shortest path between vertices A and G using Dijkstra's algorithm.\n**(d)** Write a Prim's algorithm for Minimum Spanning Tree (MST).\n**(e)** Estimate the time complexity of the Prim's algorithm for MST based on the answer in Q3(d).",
        "intuition": "**(a)** Adjacency matrix (vertices in order A,B,C,D,E,F,G):",
        "code": "A  B  C  D  E  F  G\nA  0  4  8  \u221e  \u221e  \u221e  \u221e\nB  4  0  \u221e  7  \u221e  \u221e  \u221e\nC  8  \u221e  0 10  \u221e  \u221e  \u221e\nD  \u221e  7 10  0 12 17  \u221e\nE  \u221e  \u221e  \u221e 12  0  9  6\nF  \u221e  \u221e  \u221e 17  9  0  9\nG  \u221e  \u221e  \u221e  \u221e  6  9  0",
        "execution": "**(b)** Adjacency list:\nA: \\[(B,4), (C,8)]\nB: \\[(A,4), (D,7)]\nC: \\[(A,8), (D,10)]\nD: \\[(B,7), (C,10), (E,12), (F,17)]\nE: \\[(D,12), (F,9), (G,6)]\nF: \\[(D,17), (E,9), (G,9)]\nG: \\[(E,6), (F,9)]\n\n**(c)** Dijkstra from A to G:\nInitialize dist: A=0, others \u221e.\nStep1: A: update B=4, C=8.\nStep2: B (4): update D=11.\nStep3: C (8): update D via C: 18, keep 11.\nStep4: D (11): update E=23, F=28.\nStep5: E (23): update F via E: 32 (keep 28), update G=29.\nStep6: F (28): update G via F: 37 (keep 29).\nStep7: G (29) reached. Shortest path A\u2192B\u2192D\u2192E\u2192G with total 4+7+12+6 = 29.\nAlternative: A\u2192B\u2192D\u2192F\u2192G: 4+7+17+9=37, A\u2192C\u2192D\u2192E\u2192G: 8+10+12+6=36. So shortest is 29.\n\n**(d)** Prim's algorithm implementation:\n\n```python\ndef prim_mst(graph, start=0):\n    \"\"\"\n    graph: adjacency list, e.g., [[(1,4), (2,8)], ...]\n    Returns list of (u, v, weight) for MST.\n    \"\"\"\n    n = len(graph)\n    visited = [False]*n\n    min_edge = [(float('inf'), -1)] * n   # (weight, parent)\n    min_edge[start] = (0, -1)\n    mst_edges = []\n    for _ in range(n):\n        # find unvisited vertex with smallest min_edge\n        u = -1\n        best = float('inf')\n        for i in range(n):\n            if not visited[i] and min_edge[i][0] < best:\n                best = min_edge[i][0]\n                u = i\n        visited[u] = True\n        if min_edge[u][1] != -1:\n            mst_edges.append((min_edge[u][1], u, best))\n        for v, w in graph[u]:\n            if not visited[v] and w < min_edge[v][0]:\n                min_edge[v] = (w, u)\n    return mst_edges\n```\n\n**(e)** Time complexity: With adjacency matrix, O(V\u00b2). With binary heap and adjacency list, O((V+E) log V). The provided pseudocode (from figure) likely uses adjacency matrix, so O(V\u00b2).\n\n---"
    },
    {
        "exam": "EXAM 5: SEM I 2022/2023",
        "title": "Q1 \u2014 Extended Dijkstra's Algorithm (20 marks)",
        "question": "Figure Q1 shows the Dijkstra's algorithm for finding the length of a shortest path between two vertices in a weighted simple connected graph. Extend it so that a shortest path between these vertices is constructed.",
        "intuition": "See Exam 1 Q1 \u2013 the extension adds a predecessor array and path reconstruction. Python code is provided there.\n\n---",
        "code": "",
        "execution": ""
    },
    {
        "exam": "EXAM 5: SEM I 2022/2023",
        "title": "Q2 \u2014 Dijkstra's with Negative Weights (20 marks)",
        "question": "Using Figure Q2, show that the Dijkstra's algorithm may not work if edges can have negative weights.\n\n**Figure Q2** (edge list):\n\n| Source | Destination | Weight |\n| ------ | ----------- | ------ |\n| S      | A           | 2      |\n| S      | B           | 1      |\n| S      | C           | 3      |\n| A      | E           | 2      |\n| B      | D           | -4     |\n| C      | E           | 1      |\n| C      | A           | 3      |\n| D      | E           | 2      |\n| B      | C           | 3      |",
        "intuition": "We run Dijkstra from S.\nInitialize: L(S)=0, others \u221e.\nSelect S: update A=2, B=1, C=3. S={S}.\nSelect B (1): update D = 1+(-4) = -3. S={S,B}.\nSelect A (2): update E = 2+2=4. S={S,B,A}.\nSelect D (-3): update E = -3+2 = -1 (improvement!). S={S,B,A,D}.\nSelect C (3): no update to E (E already -1). S={S,B,A,D,C}.\nSelect E (-1): done.\n\nDijkstra settles vertices as it goes; when A was settled, its distance 2 was considered final, but later a better path to E came through D, which was discovered later. The distance to E improved from 4 to -1, but E had not been settled yet, so that\u2019s okay. However, the real failure occurs if a settled vertex later gets a better distance via a negative edge. In this graph, no settled vertex was improved. But consider a graph where a negative edge goes from a later vertex back to a settled vertex. For instance, if there were an edge D->A with negative weight, then A's distance would improve after A was settled, causing incorrect results.\n\nThus, Dijkstra fails with negative weights because it assumes non-negative edges.\n\n---",
        "code": "",
        "execution": ""
    },
    {
        "exam": "EXAM 5: SEM I 2022/2023",
        "title": "Q3 \u2014 Kruskal's Algorithm (20 marks)",
        "question": "The roads represented by the graph in Figure Q3.2 are all unpaved. The lengths of the roads between pairs of towns are represented by edge weights. Use Kruskal's algorithm in Figure Q3.1 to find which roads should be paved so that there is a path of paved roads between each pair of towns so that a minimum road length is paved.\n\n**Edges (from Figure Q3.2):**\n\n| Source       | Destination  | Weight |\n| ------------ | ------------ | ------ |\n| Manhattan    | Tonopah      | 25     |\n| Manhattan    | Warm Springs | 60     |\n| Tonopah      | Warm Springs | 55     |\n| Tonopah      | Goldfield    | 35     |\n| Tonopah      | Dyer         | 40     |\n| Goldfield    | Silver Pea   | 20     |\n| Goldfield    | Beatty       | 70     |\n| Silver Pea   | Lida         | 25     |\n| Silver Pea   | Dyer         | 25     |\n| Lida         | Gold Point   | 12     |\n| Lida         | Oasis        | 25     |\n| Oasis        | Deep Springs | 10     |\n| Oasis        | Dyer         | 21     |\n| Deep Springs | Gold Point   | 30     |\n| Gold Point   | Beatty       | 45     |\n| Dyer         | Beatty       | 80     |",
        "intuition": "We sort edges by weight. List includes 16 edges. Vertices: Manhattan, Tonopah, Warm Springs, Goldfield, Silver Pea, Beatty, Lida, Gold Point, Oasis, Deep Springs, Dyer (11 vertices). MST has 10 edges.\n\nSorted edges (low to high):\n\n1. Oasis\u2013Deep Springs (10)\n2. Lida\u2013Gold Point (12)\n3. Goldfield\u2013Silver Pea (20)\n4. Oasis\u2013Dyer (21)\n5. Manhattan\u2013Tonopah (25)\n6. Silver Pea\u2013Lida (25)\n7. Silver Pea\u2013Dyer (25)\n8. Tonopah\u2013Goldfield (35)\n9. Tonopah\u2013Dyer (40)\n10. Gold Point\u2013Beatty (45)\n11. Tonopah\u2013Warm Springs (55)\n12. Manhattan\u2013Warm Springs (60)\n13. Goldfield\u2013Beatty (70)\n14. Dyer\u2013Beatty (80)\n\nNow apply Kruskal, adding if no cycle:\n\n- Add Oasis\u2013Deep Springs (10)\n- Add Lida\u2013Gold Point (12)\n- Add Goldfield\u2013Silver Pea (20)\n- Add Oasis\u2013Dyer (21)\n- Add Manhattan\u2013Tonopah (25)\n- Add Silver Pea\u2013Lida (25) \u2013 connects components\n- Add Silver Pea\u2013Dyer (25) \u2013 connects Silver Pea component with Dyer component (both separate? after previous, yes, they are separate because Dyer is with Oasis, Silver Pea with Goldfield/Lida, so add)\n- Add Tonopah\u2013Goldfield (35) \u2013 connects Manhattan-Tonopah to Goldfield component\n- Skip Tonopah\u2013Dyer (40) \u2013 would cycle\n- Add Gold Point\u2013Beatty (45) \u2013 adds Beatty\n- Add Tonopah\u2013Warm Springs (55) \u2013 adds Warm Springs\n\nNow we have 10 edges. Total weight = 10+12+20+21+25+25+25+35+45+55 = 273.\n\nSo the roads to pave: Oasis-Deep Springs, Lida-Gold Point, Goldfield-Silver Pea, Oasis-Dyer, Manhattan-Tonopah, Silver Pea-Lida, Silver Pea-Dyer, Tonopah-Goldfield, Gold Point-Beatty, Tonopah-Warm Springs.\n\n---",
        "code": "",
        "execution": ""
    },
    {
        "exam": "EXAM 5: SEM I 2022/2023",
        "title": "Q4 \u2014 Maximum Spanning Tree (20 marks)",
        "question": "A maximum spanning tree of a connected weighted undirected graph is a spanning tree with the largest possible weight. Devise an algorithm similar to Kruskal's algorithm in Figure Q3.1 for constructing a maximum spanning tree of a connected weighted graph.",
        "intuition": "Same as Exam 1 Q4 \u2013 sort edges descending and apply union-find.\n\n---",
        "code": "",
        "execution": ""
    },
    {
        "exam": "EXAM 5: SEM I 2022/2023",
        "title": "Q5 \u2014 Minimum Spanning Forest (20 marks)",
        "question": "A minimum spanning forest in a weighted graph is a spanning forest with minimal weight. Explain how Prim's algorithm, which is represented in Figure Q5, and Kruskal's algorithm in Figure Q3.1 can be adapted to construct minimum spanning forests.",
        "intuition": "See Exam 1 Q5.\n\n---",
        "code": "",
        "execution": ""
    },
    {
        "exam": "EXAM 6: SEM II 2023/2024",
        "title": "Q7 \u2014 Quick Sort (12 marks total)",
        "question": "**(a)** Write a quick sort algorithm for a set of numbers {a\u2081, a\u2082, ..., a\u2099}.\n**(b)** Sort the numbers {9, 14, 6, 16, 12, 27, 3} using the quick sort algorithm.\n**(c)** Specify the design technique type of the quick sort algorithm.\n**(d)** Estimate the best case complexity of the quick sort algorithm.",
        "intuition": "**(a)** Quick sort implementation:",
        "code": "def quicksort(arr, low, high):\n    if low < high:\n        pi = partition(arr, low, high)\n        quicksort(arr, low, pi-1)\n        quicksort(arr, pi+1, high)\n\ndef partition(arr, low, high):\n    pivot = arr[high]   # choose last element as pivot\n    i = low - 1\n    for j in range(low, high):\n        if arr[j] <= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    arr[i+1], arr[high] = arr[high], arr[i+1]\n    return i+1",
        "execution": "**(b)** Sorting \\[9,14,6,16,12,27,3]:\nChoose pivot 3 (last). Partition: \\[3, 9,6,16,12,27,14] with pivot index 1.\nLeft: \\[3] sorted. Right: \\[9,6,16,12,27,14] pivot 14 \u2192 partition: \\[9,6,12,14,27,16] pivot at 3.\nLeft of 14: \\[9,6,12] pivot 12 \u2192 \\[6,9,12] sorted. Right of 14: \\[27,16] pivot 16 \u2192 \\[16,27] sorted.\nFinal: \\[3,6,9,12,14,16,27].\n\n**(c)** Divide and Conquer.\n\n**(d)** Best-case complexity: O(n log n) when pivot divides array evenly.\n\n---\n\n#"
    },
    {
        "exam": "EXAM 6: SEM II 2023/2024",
        "title": "Q8 \u2014 Recursive Algorithms (25 marks total)",
        "question": "**(a)** Write a recursive algorithm to compute the nth Fibonacci number.\n**(b)** Implement a recursive version of the binary search algorithm.\n**(c)** Estimate the time complexity of the algorithm in Q8(b).\n**(d)** Use the algorithm in Q8(b) to search for the number 19 in the set {10, 13, 16, 18, 19, 21, 23, 26}.\n**(e)** Use the algorithm in Q8(b) to search for the number 15 in the same set.\n**(f)** Estimate the time complexity of the algorithm in processing Q8(e).",
        "intuition": "**(a)** Fibonacci:",
        "code": "def fib(n):\n    if n == 0:\n        return 0\n    elif n == 1:\n        return 1\n    else:\n        return fib(n-1) + fib(n-2)",
        "execution": "**(b)** Recursive binary search (same as before).\n\n**(c)** Time complexity: O(log n) because each call reduces search space by half.\n\n**(d)** Search 19 in \\[10,13,16,18,19,21,23,26]:\nlow=0, high=7, mid=3 (18) < 19 \u2192 right. low=4, high=7, mid=5 (21) > 19 \u2192 left. low=4, high=4, mid=4 (19) found.\n\n**(e)** Search 15: low=0, high=7, mid=3 (18) > 15 \u2192 left. low=0, high=2, mid=1 (13) < 15 \u2192 right. low=2, high=2, mid=2 (16) > 15 \u2192 left. low=2, high=1 \u2192 stop, return -1 (not found).\n\n**(f)** Complexity remains O(log n) even when not found.\n\n---\n\n#"
    },
    {
        "exam": "EXAM 6: SEM II 2023/2024",
        "title": "Q9 \u2014 Graph Theory (15 marks total)",
        "question": "Given the following weighted graph (table):\n\n| Source | Destination | Weight |\n| ------ | ----------- | ------ |\n| A      | B           | 1      |\n| A      | C           | 2      |\n| B      | D           | 3      |\n| C      | D           | 4      |\n| C      | E           | 5      |\n| D      | F           | 6      |\n| E      | F           | 7      |\n\n**(a)** Find the adjacency matrix of the weighted graph.\n**(b)** Find the adjacency list of the weighted graph.\n**(c)** Use Dijkstra's algorithm to find the shortest path from district A to district F.",
        "intuition": "**(a)** Vertices: A,B,C,D,E,F. Matrix:",
        "code": "A  B  C  D  E  F\nA  0  1  2  \u221e  \u221e  \u221e\nB  1  0  \u221e  3  \u221e  \u221e\nC  2  \u221e  0  4  5  \u221e\nD  \u221e  3  4  0  \u221e  6\nE  \u221e  \u221e  5  \u221e  0  7\nF  \u221e  \u221e  \u221e  6  7  0",
        "execution": "**(b)** Adjacency list:\nA: \\[(B,1), (C,2)]\nB: \\[(A,1), (D,3)]\nC: \\[(A,2), (D,4), (E,5)]\nD: \\[(B,3), (C,4), (F,6)]\nE: \\[(C,5), (F,7)]\nF: \\[(D,6), (E,7)]\n\n**(c)** Dijkstra from A to F:\nInitialize dist: A=0, others \u221e.\nPop A: update B=1, C=2.\nPop B (1): update D=4.\nPop C (2): update D via C: 6 (keep 4), update E=7.\nPop D (4): update F=10.\nPop E (7): update F via E: 14 (keep 10).\nPop F (10) \u2013 target reached. Shortest path: A\u2192B\u2192D\u2192F with total 1+3+6=10. (Alternative A\u2192C\u2192E\u2192F: 2+5+7=14, A\u2192C\u2192D\u2192F: 2+4+6=12). So shortest is 10."
    }
];
